INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_EMULATE_HARDWARE emulate_hardware)

FIND_PATH(
    EMULATE_HARDWARE_INCLUDE_DIRS
    NAMES emulate_hardware/api.h
    HINTS $ENV{EMULATE_HARDWARE_DIR}/include
        ${PC_EMULATE_HARDWARE_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREEFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    EMULATE_HARDWARE_LIBRARIES
    NAMES gnuradio-emulate_hardware
    HINTS $ENV{EMULATE_HARDWARE_DIR}/lib
        ${PC_EMULATE_HARDWARE_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(EMULATE_HARDWARE DEFAULT_MSG EMULATE_HARDWARE_LIBRARIES EMULATE_HARDWARE_INCLUDE_DIRS)
MARK_AS_ADVANCED(EMULATE_HARDWARE_LIBRARIES EMULATE_HARDWARE_INCLUDE_DIRS)

